const kvpData = [
    {
        "Sname": "Sanjana Bhagwan Agiwale",
        "Gender ": "F",
        "SAddress": "At Po. Shirol, Ta. Shahapur, Dist. Thane ",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9028801821",
        "AadharNo": "2946 9545 0771",
        "DOB": "2010-02-02",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Puja Chander Aare",
        "Gender ": "F",
        "SAddress": "At.KharAtyachapada . Ta. Shahapur, Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "7066892834",
        "AadharNo": "3840 9485 3050",
        "DOB": "2009-09-24",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Kiran Sakru Amle",
        "Gender ": "F",
        "SAddress": "At. Balwandi, , Ta. Shahapur,  Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "7350519154",
        "AadharNo": "5881 9488 2718",
        "DOB": "2010-03-07",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Sadhana Bandu Bagul",
        "Gender ": "F",
        "SAddress": "At. Khairpada  Ta. Shahapur, . Thane",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "9668938189",
        "AadharNo": "8496 7001 2676",
        "DOB": "2009-08-03",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Karuna Namdev Bangara",
        "Gender ": "F",
        "SAddress": "At. Kochre, Ta. Atrbad, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "Thakur",
        "ContactNum": "9021458059",
        "AadharNo": "2062 5640 8468",
        "DOB": "2010-02-06",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Savita Kisan Bhagat",
        "Gender ": "F",
        "SAddress": "At. bhagatpada , Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9370736649",
        "AadharNo": "9295 3190 2660",
        "DOB": "2010-04-08",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Komal Bharat Bhala",
        "Gender ": "F",
        "SAddress": "At. DhenganAtal, .Ta. Shahapur. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "8767152330",
        "AadharNo": "9116 2774 2777",
        "DOB": "2009-09-14",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Pinky Halya Bhala",
        "Gender ": "F",
        "SAddress": "At. Balwandi,  Ta. Shahapur, Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9307871612",
        "AadharNo": "8359 3937 9439",
        "DOB": "2009-06-05",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Priyanka Tukaram Bhangare",
        "Gender ": "F",
        "SAddress": "At Po. Ekdare, Ta. Akole, Dist. AhAtadnagar",
        "Caste": "S.T",
        "SubCaste": "Maha. koli",
        "ContactNum": "9370479929",
        "AadharNo": "7799 2181 7013",
        "DOB": "2009-11-13",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Tejakshee Lalu Bhangre",
        "Gender ": "F",
        "SAddress": "At, UAtbarAtali, Ta. Shahapur. Thane ",
        "Caste": "S.T",
        "SubCaste": "Maha. koli",
        "ContactNum": "9579816831",
        "AadharNo": "2524 7413 8635",
        "DOB": "2009-11-20",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Deepali Pandit Bonge",
        "Gender ": "F",
        "SAddress": "At. TeAtbhe,  Ta. Shahapur,Thane",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "8459996237",
        "AadharNo": "6042 9353 0818",
        "DOB": "2009-09-01",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Harshali Pintu Chaudhari",
        "Gender ": "F",
        "SAddress": "At, taAtbadAtal, Ta. Shahapur, . Thane ",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "7743868531",
        "AadharNo": "9098 9537 9968",
        "DOB": "2009-03-15",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Gauri Eknath Chikhale",
        "Gender ": "F",
        "SAddress": "At. Terugan, Ta. Akole, Dist. AhAtednagar",
        "Caste": "S.T",
        "SubCaste": "Maha. koli",
        "ContactNum": "9545540253",
        "AadharNo": "6011 3713 3372 ",
        "DOB": "2009-11-20",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Aatara Vasant Dhapte",
        "Gender ": "F",
        "SAddress": "At Po. Shirol, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9175142746",
        "AadharNo": "7656 8144 2881 ",
        "DOB": "2009-06-03",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Manisha Shaneshwar Dhapate",
        "Gender ": "F",
        "SAddress": "At.AAtBYACHIWADI,  Ta. Shahapur, Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9370643166",
        "AadharNo": "5200 0915 5773",
        "DOB": "2010-01-04",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Nikita Anant Dhapte",
        "Gender ": "F",
        "SAddress": "At. Po. Shirol, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "7719808146",
        "AadharNo": "6920 8422 3789 ",
        "DOB": "2009-03-02",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Tamanna Jaanu Dhapte",
        "Gender ": "F",
        "SAddress": "At. Balwandi, Ta. Shahapur,. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "7719023607",
        "AadharNo": "7590 0529 1309",
        "DOB": "2010-09-25",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Diksha Ankush Gangad",
        "Gender ": "F",
        "SAddress": "At. Balwandi, Ta. Shahapur, Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "8108361944",
        "AadharNo": "8701 5322 4964 ",
        "DOB": "2009-02-17",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Gayatri Kashinath Gangad",
        "Gender ": "F",
        "SAddress": "At.DolkhaAtb, Ta. Shahapur, Dist. Thane ",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9373829146",
        "AadharNo": "3840 6924 9479 ",
        "DOB": "2009-05-24",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": " Kirti Sakharam Gangad",
        "Gender ": "F",
        "SAddress": "At. Balwandi,  Ta. Shahapur, . Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "7744829720",
        "AadharNo": "9502 2469 0154",
        "DOB": "2009-07-07",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Yojana Yashvant Gavanda",
        "Gender ": "F",
        "SAddress": "At, fugala, Ta. Shahapur, . Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9604531304",
        "AadharNo": "2033 9445 5615",
        "DOB": "2010-04-10",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Kalpana Madhu Gira",
        "Gender ": "F",
        "SAddress": "At. Dhadyachapada .Ta. Shahapur, Thane ",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9767517341",
        "AadharNo": "4618 4777 3672",
        "DOB": "2010-06-23",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Rohini Ravaji Gira",
        "Gender ": "F",
        "SAddress": "At.Babarwadi,  Ta. Shahapur, Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9022655700",
        "AadharNo": "9731 4868 9625",
        "DOB": "2009-01-22",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Payal Ashok Hirva",
        "Gender ": "F",
        "SAddress": "At. NaAtpada, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "NA",
        "AadharNo": "3077 4057 3157",
        "DOB": "2010-12-14",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Chandrabhaga Raju kachare",
        "Gender ": "F",
        "SAddress": "At. Waranghushi, Ta. Akole, Dist. AhAtednagar",
        "Caste": "S.T",
        "SubCaste": "Maha. koli",
        "ContactNum": "NA",
        "AadharNo": "2900 0370 0066",
        "DOB": "2010-11-16",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Jiya Girish Kamdi",
        "Gender ": "F",
        "SAddress": "At. Vashind, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "NA",
        "AadharNo": "9674 9636 4756 ",
        "DOB": "2010-05-06",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Sanjivani Dasharath Khadake",
        "Gender ": "F",
        "SAddress": "At, Janval, Ta. Bhiwandi, Dist. Thane ",
        "Caste": "S.T",
        "SubCaste": "Thakur",
        "ContactNum": "9022624664",
        "AadharNo": "5582 6553 1077",
        "DOB": "2010-05-06",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Kalyani Ashok Khandvi",
        "Gender ": "F",
        "SAddress": "At. doryachapada,  Ta. Shahapur, Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "NA",
        "AadharNo": "5447 9052 2895 ",
        "DOB": "2010-05-04",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Maya Bhaskar Khandvi",
        "Gender ": "F",
        "SAddress": "At. doryachapada,  Ta. Shahapur, Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "8668641638",
        "AadharNo": "4328 2447 7508 ",
        "DOB": "2009-09-30",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Suvarna Sunil Khandvi",
        "Gender ": "F",
        "SAddress": "At. Babrewadi, Ta. Shahapur,  Thane ",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9527891774",
        "AadharNo": "7487 4614 1536",
        "DOB": "2010-03-29",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Anjali Hanumant Khodaka",
        "Gender ": "F",
        "SAddress": "At. JaAtbhulwadi,Ta Atrbad, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "8459379053",
        "AadharNo": "3510 1707 6739",
        "DOB": "2010-11-28",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Guddi Govind Khodka",
        "Gender ": "F",
        "SAddress": "At. JaAtbhulwadi,Ta Atrbad, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "Thakur",
        "ContactNum": "7039765150",
        "AadharNo": "6145 4323 8620",
        "DOB": "2010-07-09",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Kalyani Rohidas korade",
        "Gender ": "F",
        "SAddress": "At I.G Hospital Ta Bhiwandi. ",
        "Caste": "S.T",
        "SubCaste": "Maha. koli",
        "ContactNum": "9273743761",
        "AadharNo": "9422 0421 4874",
        "DOB": "2010-03-17",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Sonu Bhagwan Lote",
        "Gender ": "F",
        "SAddress": "At. Khairpada ,Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "NA",
        "AadharNo": "8656 7538 5302",
        "DOB": "2010-08-25",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Sapana Bharat Madha",
        "Gender ": "F",
        "SAddress": "KharaAtyachapada .Ta. Shahapur,  Thane ",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "8999982902",
        "AadharNo": "9627 0062 4717",
        "DOB": "2010-11-29",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Disha Tukaram Mengal",
        "Gender ": "F",
        "SAddress": "At. Doryachapada Ta. Shahapur,  Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "NA",
        "AadharNo": "9385 1406 1683",
        "DOB": "2010-07-23",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Apeksha Ananta Nirguda",
        "Gender ": "F",
        "SAddress": "At. NaAtpada, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "8788409770",
        "AadharNo": "3603 4728 2192",
        "DOB": "2009-11-22",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Shamika Maloji Nirguda",
        "Gender ": "F",
        "SAddress": "At. NaAtpada, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9225592991",
        "AadharNo": "4041 9234 3094",
        "DOB": "2010-04-06",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Sonu Vaman Nirguda",
        "Gender ": "F",
        "SAddress": "At. NaAtpada, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "NA",
        "AadharNo": "9993 0807 1107",
        "DOB": "2009-09-05",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Sneha Santosh Pathare",
        "Gender ": "F",
        "SAddress": "At, Khanshet, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "7972279981",
        "AadharNo": "2058 7956 6131",
        "DOB": "2010-08-01",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Anjali Kalu Thakare",
        "Gender ": "F",
        "SAddress": "At aghai, Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "8668863895",
        "AadharNo": "3116 6597 9014",
        "DOB": "2010-09-24",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Punam Subhash Thombre",
        "Gender ": "F",
        "SAddress": "At AAtbyachiwadi Ta. Shahapur,Thane ",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "9270591326",
        "AadharNo": "7481 0886 5977",
        "DOB": "2009-01-08",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Anju Suresh Vad",
        "Gender ": "F",
        "SAddress": "At. Khairpada  Ta. Shahapur, Thane",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "9552836804",
        "AadharNo": "9293 3030 8957",
        "DOB": "2010-04-18",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Sarika Pandhari Wad",
        "Gender ": "F",
        "SAddress": "At. Khairpada Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "9527987399",
        "AadharNo": "7229 9562 7180",
        "DOB": "2009-12-22",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Ashwini Prakash Vatas",
        "Gender ": "F",
        "SAddress": "At. TaAtbadAtal, Ta. Shahapur, Dist. Thane ",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "9209117761",
        "AadharNo": "7707 5507 7786",
        "DOB": "2010-12-15",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Rajashri Laxman Vatas",
        "Gender ": "F",
        "SAddress": "At. Gotheghar, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "9518977864",
        "AadharNo": "6471 3123 1897",
        "DOB": "2009-12-10",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Usha Ashok Vatas",
        "Gender ": "F",
        "SAddress": "At. TaAtbadAtal, Ta. Shahapur, Dist. Thane ",
        "Caste": "S.T",
        "SubCaste": "Varali",
        "ContactNum": "9146926539",
        "AadharNo": "2822 5406 2769",
        "DOB": "2010-12-02",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Neha Somnath Mondula",
        "Gender ": "F",
        "SAddress": "At. PAYARWADI, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "NA",
        "AadharNo": "5299 9162 0488",
        "DOB": "2010-01-20",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Jyothika Gurunath Shid",
        "Gender ": "F",
        "SAddress": "At. Chinchwadi, Ta. Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "7498754117",
        "AadharNo": "5415 6094 1510",
        "DOB": "2009-02-21",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Nayana Ashwin Baratad",
        "Gender ": "F",
        "SAddress": "At Talwade Ta Shahapur Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "NA",
        "AadharNo": "6876 2613 9192",
        "DOB": "2009-06-25",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Yogita Prakash Sable",
        "Gender ": "F",
        "SAddress": "At Talwade Ta Shahapur Dist. Thane ",
        "Caste": "S.T",
        "SubCaste": "Maha. koli",
        "ContactNum": "8208178586",
        "AadharNo": "3185 2983 6694",
        "DOB": "2009-07-18",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Harshada Harichandra Bhala",
        "Gender ": "F",
        "SAddress": "At Shirol Ta Shahapur Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "8180826661",
        "AadharNo": "8718 0690 4812",
        "DOB": "2010-01-10",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Jagruti Balu Mengal",
        "Gender ": "F",
        "SAddress": "At shidpada Ta Shahapur Dist. Thane ",
        "Caste": "S.T",
        "SubCaste": "M. Thakur ",
        "ContactNum": "NA",
        "AadharNo": "7501 7616 0103",
        "DOB": "2010-05-15",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Mamata Sriram Wagh",
        "Gender ": "F",
        "SAddress": "At. Atal, Ta Atrbad, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "Thakur",
        "ContactNum": "NA",
        "AadharNo": "4831 1894 3598",
        "DOB": "2010-04-18",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    },
    {
        "Sname": "Aankita Sakaru marade",
        "Gender ": "F",
        "SAddress": "At Talwade Ta Shahapur, Dist. Thane",
        "Caste": "S.T",
        "SubCaste": "Maha. koli",
        "ContactNum": "9657401947",
        "AadharNo": "7448 6010 6862",
        "DOB": "2010-06-13",
        "Taluka": "Shahapur",
        "Std": 9,
        "School": "Kulhe Shenva Ashram School",
        "Class": 1,
        "Group": "Hirkani",
        "HOD": "Kavita Padval",
        "Supervisor": "Supriya Madam",
        "KishoriTai": "Dipti Harne"
    }
];

module.exports = { data: kvpData };